# linux环境下的配置

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.14.45.117:3306/common-springboot?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8&useSSL=false
    username: root
    password: mhs-mysql4001051166

download:
  # 文件下载地址
  url: http://106.14.45.117:8055/common/upload/download?name=
  # 图片存放路径
  path: /usr/local/java/upload-server/upload/