# windows环境下的配置

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.34.137.166:3306/common-springboot?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8&useSSL=false
    username: root
    password:

download:
  # 文件下载地址
  url: http://localhost:8055/common/upload/download?name=
  # 图片存放路径
  path: D:\project\My\upload\